# Site settings
title:          Lianne's Archive 💭
description:    "Lianne Choi"
baseurl:        ""
url:            "https://lianne-b.github.io"

# Google Analytics
google_analytics: G-ETJPR6E0TN

# Author
author:
  name:         lianne
  url:          https://lianne-b.github.io/
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale